# Generated by Django 5.0.6 on 2024-07-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="businessid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subscriptionsid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="department_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="usercore.departments",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_time_from",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_time_to",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="businessid",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="usercore.businessid",
            ),
        ),
        migrations.CreateModel(
            name="subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(verbose_name="Start_Date")),
                ("end_date", models.DateTimeField()),
                ("is_valid", models.BooleanField(default=False)),
                ("amount", models.FloatField(editable=False)),
                ("duration", models.DurationField(editable=False)),
                ("Discount", models.FloatField(editable=False)),
                ("transaction_id", models.CharField(max_length=30)),
                (
                    "businessid",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
                (
                    "subscriptionid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.subscriptionsid",
                    ),
                ),
            ],
            options={
                "permissions": [("is_admin", "checks if the user is an admin.")],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                default="0000",
                on_delete=django.db.models.deletion.PROTECT,
                to="usercore.subscriptionsid",
            ),
        ),
    ]
