# Generated by Django 5.0.6 on 2024-07-21 13:13

import usercore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0004_alter_user_insurance_add_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gstin_Number",
            field=models.CharField(
                max_length=15,
                null=True,
                validators=[usercore.models.validate_gstin],
                verbose_name="GSTIN Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="businessName",
            field=models.CharField(max_length=40, verbose_name="Business Name"),
        ),
    ]
