# Generated by Django 5.0.6 on 2024-07-21 14:09

import usercore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0005_user_gstin_number_alter_user_businessname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_contact",
            field=models.IntegerField(
                help_text="Enter your Phone Number.",
                validators=[usercore.models.validate_phone],
                verbose_name="Phone Number(+91 only)",
            ),
        ),
    ]
