# Generated by Django 5.0.6 on 2024-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0006_alter_user_last_name_alter_user_phone_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
    ]
