# Generated by Django 5.0.6 on 2024-07-21 14:29

import usercore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0007_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gstin_Number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[usercore.models.validate_gstin],
                verbose_name="GSTIN Number",
            ),
        ),
    ]
