# Generated by Django 5.0.6 on 2024-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0008_alter_user_gstin_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptions",
            options={},
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="payment_status",
            field=models.CharField(
                choices=[("pass", "pass"), ("fail", "fail")],
                default="fail",
                max_length=10,
            ),
        ),
    ]
