# Generated by Django 5.0.6 on 2024-07-22 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0009_alter_subscriptions_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
