# Generated by Django 5.0.6 on 2024-07-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0011_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="usercore.departments",
            ),
        ),
    ]
