# Generated by Django 5.0.6 on 2024-07-23 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0012_alter_user_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin_user",
        ),
    ]
