# Generated by Django 5.0.6 on 2024-07-24 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0013_remove_user_admin_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Insurance_add_access",
            new_name="insurance_add_access",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Insurance_delete_access",
            new_name="insurance_delete_access",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Insurance_read_access",
            new_name="insurance_read_access",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Insurance_update_access",
            new_name="insurance_update_access",
        ),
    ]
