# Generated by Django 5.0.2 on 2024-07-30 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "usercore",
            "0014_rename_insurance_add_access_user_insurance_add_access_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("is_admin", "checks if the user is admin or not.")]
            },
        ),
    ]
