# Generated by Django 5.2.4 on 2025-07-29 21:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usercore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usercore", "0015_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_add_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_delete_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_read_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="insurance_update_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stock_add_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stock_delete_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stock_read_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stock_update_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sub_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workshop_add_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workshop_delete_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workshop_read_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workshop_update_access",
        ),
        migrations.CreateModel(
            name="EmployeeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("employeeID", models.IntegerField(verbose_name="Employee ID")),
                (
                    "phone_contact",
                    models.IntegerField(
                        help_text="Enter your Phone Number.",
                        validators=[usercore.models.validate_phone],
                        verbose_name="Phone Number(+91 only)",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Address"
                    ),
                ),
                ("login_time_to", models.TimeField(null=True)),
                (
                    "add_package",
                    models.BooleanField(default=False, verbose_name="add packages"),
                ),
                (
                    "update_package",
                    models.BooleanField(default=False, verbose_name="update packages"),
                ),
                (
                    "delete_package",
                    models.BooleanField(default=False, verbose_name="delete packages"),
                ),
                (
                    "view_package",
                    models.BooleanField(default=False, verbose_name="view packages"),
                ),
                (
                    "all_perm_packages",
                    models.BooleanField(
                        default=False, verbose_name="all permissions packages"
                    ),
                ),
                (
                    "add_team",
                    models.BooleanField(default=False, verbose_name="add team"),
                ),
                (
                    "update_team",
                    models.BooleanField(default=False, verbose_name="update team"),
                ),
                (
                    "delete_team",
                    models.BooleanField(default=False, verbose_name="delete team"),
                ),
                (
                    "view_team",
                    models.BooleanField(default=False, verbose_name="view team"),
                ),
                (
                    "add_members",
                    models.BooleanField(default=False, verbose_name="add members"),
                ),
                (
                    "deactivate_members",
                    models.BooleanField(
                        default=False, verbose_name="deactivate members"
                    ),
                ),
                (
                    "activate_members",
                    models.BooleanField(default=False, verbose_name="activate members"),
                ),
                (
                    "all_perm_team",
                    models.BooleanField(
                        default=False, verbose_name="all permissions teams"
                    ),
                ),
                (
                    "view_network_package",
                    models.BooleanField(
                        default=False, verbose_name="view network packages"
                    ),
                ),
                (
                    "approve_network_package",
                    models.BooleanField(
                        default=False, verbose_name="approve network packages"
                    ),
                ),
                (
                    "create_insurance_track",
                    models.BooleanField(
                        default=False, verbose_name="create insurance track"
                    ),
                ),
                (
                    "update_insurance_track",
                    models.BooleanField(
                        default=False, verbose_name="update insurance track"
                    ),
                ),
                (
                    "delete_insurance_track",
                    models.BooleanField(
                        default=False, verbose_name="delete insurance track"
                    ),
                ),
                (
                    "view_insurance_track",
                    models.BooleanField(
                        default=False, verbose_name="view insurance track"
                    ),
                ),
                (
                    "all_perm_insurance_track",
                    models.BooleanField(
                        default=False, verbose_name="all permissions insurance track"
                    ),
                ),
                (
                    "create_item",
                    models.BooleanField(default=False, verbose_name="create item"),
                ),
                (
                    "update_item",
                    models.BooleanField(default=False, verbose_name="update item"),
                ),
                (
                    "delete_item",
                    models.BooleanField(default=False, verbose_name="delete item"),
                ),
                (
                    "view_items",
                    models.BooleanField(default=False, verbose_name="view item"),
                ),
                (
                    "add_stock",
                    models.BooleanField(default=False, verbose_name="add stock"),
                ),
                (
                    "delete_stock",
                    models.BooleanField(default=False, verbose_name="delete stock"),
                ),
                (
                    "update_stock",
                    models.BooleanField(default=False, verbose_name="update stock"),
                ),
                (
                    "view_stock",
                    models.BooleanField(default=False, verbose_name="view stock"),
                ),
                (
                    "all_perm_stock",
                    models.BooleanField(
                        default=False, verbose_name="all permissions stock"
                    ),
                ),
                (
                    "add_task",
                    models.BooleanField(default=False, verbose_name="add task"),
                ),
                (
                    "update_task",
                    models.BooleanField(default=False, verbose_name="update task"),
                ),
                (
                    "delete_task",
                    models.BooleanField(default=False, verbose_name="delete task"),
                ),
                (
                    "view_task",
                    models.BooleanField(default=False, verbose_name="view task"),
                ),
                (
                    "all_perm_workshop",
                    models.BooleanField(
                        default=False, verbose_name="aall permissions workshop"
                    ),
                ),
                (
                    "ask_service",
                    models.BooleanField(default=False, verbose_name="ask service"),
                ),
                (
                    "start_service",
                    models.BooleanField(default=False, verbose_name="start service"),
                ),
                (
                    "stop_service",
                    models.BooleanField(default=False, verbose_name="stop service"),
                ),
                (
                    "view_service",
                    models.BooleanField(default=False, verbose_name="view service"),
                ),
                (
                    "monitor_service",
                    models.BooleanField(default=False, verbose_name="monitor service"),
                ),
                (
                    "view_feedback",
                    models.BooleanField(default=False, verbose_name="view feedback"),
                ),
                (
                    "get_feedback",
                    models.BooleanField(default=False, verbose_name="get feedback"),
                ),
                (
                    "mark_feedback",
                    models.BooleanField(default=False, verbose_name="mark feedback"),
                ),
                (
                    "businessID",
                    models.ForeignKey(
                        default="0001",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_id",
                        to="usercore.businessid",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="employeeuser_set_groups",
                        related_query_name="employeeuser",
                        to="auth.group",
                        verbose_name="employee groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="employeeuser_set_perms",
                        related_query_name="employeeuser",
                        to="auth.permission",
                        verbose_name="employee permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
