# Generated by Django 5.2.4 on 2025-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0016_remove_user_admin_access_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="department_access",
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_time_from",
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_time_to",
        ),
        migrations.AddField(
            model_name="employeeuser",
            name="all_crm_permissions",
            field=models.BooleanField(
                default=False, verbose_name="all permissions crm"
            ),
        ),
        migrations.AddField(
            model_name="employeeuser",
            name="all_perm_services",
            field=models.BooleanField(
                default=False, verbose_name="all permissions service"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_address",
            field=models.CharField(
                default="Jagdalpur", max_length=200, verbose_name="business_address"
            ),
            preserve_default=False,
        ),
    ]
