# Generated by Django 5.2.4 on 2025-08-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0018_remove_employeeuser_activate_members_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeuser",
            old_name="employeeID",
            new_name="employeeid",
        ),
        migrations.AddField(
            model_name="employeeuser",
            name="businessid",
            field=models.ForeignKey(
                default="0001",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_id",
                to="usercore.businessid",
            ),
        ),
    ]
