# Generated by Django 5.2.4 on 2025-08-06 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0019_rename_employeeid_employeeuser_employeeid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeuser",
            name="created_on",
            field=models.TimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
