# Generated by Django 5.2.4 on 2025-08-06 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usercore", "0020_employeeuser_created_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeuser",
            options={
                "default_permissions": (),
                "permissions": [
                    ("employee_is_admin", "Is the admin"),
                    ("add_package", "Can add a package"),
                    ("update_package", "Can update a package"),
                    ("delete_package", "Can delete a package"),
                    ("view_package", "Can view packages"),
                    ("all_perm_packages", "all permissions packages"),
                    ("add_team", "Can add a team"),
                    ("update_team", "Can update a team"),
                    ("delete_team", "Can delete a team"),
                    ("view_team", "Can view teams"),
                    ("add_members", "Can add members to a team"),
                    ("deactivate_members", "Can deactivate team members"),
                    ("activate_members", "Can activate team members"),
                    ("all_perm_team", "all permissions teams"),
                    ("view_network_package", "Can view network packages"),
                    ("approve_network_package", "Can approve network packages"),
                    ("create_insurance_track", "Can create an insurance track"),
                    ("update_insurance_track", "Can update an insurance track"),
                    ("delete_insurance_track", "Can delete an insurance track"),
                    ("view_insurance_track", "Can view insurance tracks"),
                    ("all_perm_insurance_track", "all permissions insurance track"),
                    ("create_item", "Can create an item"),
                    ("update_item", "Can update an item"),
                    ("delete_item", "Can delete an item"),
                    ("view_items", "Can view items"),
                    ("add_stock", "Can add stock"),
                    ("delete_stock", "Can delete stock"),
                    ("update_stock", "Can update stock"),
                    ("view_stock", "Can view stock"),
                    ("all_perm_stock", "all permissions stock"),
                    ("add_task", "Can add a task"),
                    ("update_task", "Can update a task"),
                    ("delete_task", "Can delete a task"),
                    ("view_task", "Can view tasks"),
                    ("all_perm_workshop", "all permissions workshop"),
                    ("ask_service", "Can ask for a service"),
                    ("start_service", "Can start a service"),
                    ("stop_service", "Can stop a service"),
                    ("view_service", "Can view services"),
                    ("monitor_service", "Can monitor services"),
                    ("all_perm_services", "all permissions service"),
                    ("view_feedback", "Can view feedback"),
                    ("get_feedback", "Can retrieve feedback details"),
                    ("mark_feedback", "Can mark feedback"),
                    ("all_crm_permissions", "all permissions crm"),
                ],
            },
        ),
    ]
