# Generated by Django 5.0.6 on 2024-07-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "usercore",
            "0014_rename_insurance_add_access_user_insurance_add_access_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_no", models.CharField(max_length=40)),
                ("accessories", models.JSONField()),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=40)),
                ("code_name", models.CharField(max_length=40)),
                ("colours", models.JSONField()),
                ("varients", models.JSONField()),
                ("is_accessories_included", models.BooleanField()),
                ("accessories", models.JSONField(blank=True, null=True)),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="incoming_vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_no", models.CharField(max_length=50)),
                ("seller", models.CharField(default="Factory", max_length=50)),
                ("delivery_data", models.DateField(verbose_name="Delivery Date")),
                ("invoice_no", models.CharField(max_length=50)),
                ("invoice_date", models.DateField()),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("tag", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Storage", "storage"),
                            ("Point Of Sale", "point_of_sale"),
                            ("Both", "both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="outgoing_vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_no", models.CharField(max_length=50)),
                ("engine_no", models.CharField(max_length=50)),
                ("is_delivered", models.BooleanField(default=False)),
                ("receiving_party", models.CharField(max_length=100)),
                ("damage_report", models.CharField(max_length=100)),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_no", models.CharField(max_length=40)),
                ("location", models.CharField(max_length=50)),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vehicle_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=50)),
                ("invoice_date", models.DateField()),
                ("model_name", models.CharField(max_length=50)),
                ("varient", models.CharField(max_length=50)),
                ("colour", models.CharField(max_length=50)),
                ("frame_no", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "engine_no",
                    models.CharField(blank=True, default=0, max_length=40, unique=True),
                ),
                ("is_damaged", models.BooleanField(default=True, max_length=40)),
                ("status", models.CharField(max_length=20)),
                ("date_of_delivery", models.DateTimeField(blank=True)),
                ("date_of_sale", models.DateTimeField()),
                ("storage_location", models.CharField(max_length=50)),
                ("timestamp_of_entry", models.DateTimeField()),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="damaged",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.JSONField()),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
                (
                    "frame_no",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="webcore.vehicle_entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vehicle_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_no", models.CharField(max_length=50)),
                ("engine_no", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                (
                    "businessid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usercore.businessid",
                    ),
                ),
            ],
        ),
    ]
