# Generated by Django 5.0.2 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="colours",
        ),
        migrations.RemoveField(
            model_name="categories",
            name="varients",
        ),
        migrations.AlterField(
            model_name="categories",
            name="code_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="model_name",
            field=models.JSONField(),
        ),
    ]
