# Generated by Django 5.0.2 on 2024-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webcore",
            "0002_remove_categories_colours_remove_categories_varients_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="code_name",
        ),
        migrations.AddField(
            model_name="categories",
            name="other",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categories",
            name="model_name",
            field=models.CharField(max_length=50),
        ),
    ]
